name: Build and Release Apps
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1
        with:
          channel: master
      - run: flutter doctor -v

      - name: Install web dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      # - run: npm install -g firebase-tools

      # Checkout gallery code and get packages.
      - name: Checkout repository 🛎️
        uses: actions/checkout@v2
      - run: flutter pub get

      # Build and deploy (by default, to staging).
      - run: flutter build -v web --release
      # - run: firebase deploy -P ${{ github.event.inputs.environment || 'staging' }}
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.